### ISSUE TITLE
[CRITICAL] Utilizar spread operator

### ISSUE THREAD

**Issue by ale1313** [Liichi/CocktailFinder#11]
https://github.com/Liichi/CocktailFinder/blob/c68fe20764f880d2de5694162be56d30b6c6af5c/src/reducers/search.ts#L23

Casi siempre que utilices el reducer para cambiar el state de Redux te conviene usar el spread operator para lo que seria mantener el viejo state, por ej:

`return {
...oldState,
property: newValue,
}`

**Comment by Liichi** [comment]
Arreglado
