### ISSUE TITLE
Responsive size and Normalize

### ISSUE THREAD

**Issue by IanCiarulli** [Liichi/CocktailFinder#13]
https://github.com/Liichi/CocktailFinder/blob/c68fe20764f880d2de5694162be56d30b6c6af5c/src/components/header.tsx#L83-L86
https://github.com/Liichi/CocktailFinder/blob/c68fe20764f880d2de5694162be56d30b6c6af5c/src/screens/search.tsx#L93
Para evitar comportamientos raros de los tamaños de los elementos nosotros usamos una funcion para que calcule el valor correcto en base a el alto y el ancho del dispositivo, aplica para todos los elementos con tamaño mayor a 2 y que no sean TEXT ,para esos usamos normalize , te dejo los vinculos del boilerplate donde estan ambas funciones 
ResponsiveSize: 
https://github.com/javi10823/rn-boilerplate-nextdots/blob/0.60.4-redux/src/utils/responsive.ts
Normalize (nlz):
https://github.com/javi10823/rn-boilerplate-nextdots/blob/0.60.4-redux/src/styled/index.ts

**Comment by Liichi** [comment]
Arreglado
