### ISSUE TITLE
[CRITICAL] Uso de getState()

### ISSUE THREAD

**Issue by ale1313** [Liichi/CocktailFinder#14]
https://github.com/Liichi/CocktailFinder/blob/c68fe20764f880d2de5694162be56d30b6c6af5c/src/actions/search.ts#L70

Usualmente no es bueno llamar a getState fuera de los components, lo que te recomendaría en este caso es que cuando una acción dependa del state se la pases a través de props

**Comment by Liichi** [comment]
Arreglado
