### ISSUE TITLE
[Minor] Codigo innecesario

### ISSUE THREAD

**Issue by ale1313** [Liichi/CocktailFinder#15]
https://github.com/Liichi/CocktailFinder/blob/c68fe20764f880d2de5694162be56d30b6c6af5c/src/components/cocktail/cocktail.tsx#L10

Esto no iria, si hay algo que no usas en el código (capaz lo usaste antes y te olvidaste de borrarlo) borralo y que no quede ahi

**Comment by Liichi** [comment]
Arreglado
