### ISSUE TITLE
[Minor] Uso de responsiveSize para el tamaño de fuente

### ISSUE THREAD

**Issue by ale1313** [Liichi/CocktailFinder#17]
https://github.com/Liichi/CocktailFinder/blob/c68fe20764f880d2de5694162be56d30b6c6af5c/src/components/cocktail/cocktail.tsx#L53

En otro issue @IanCiarulli te menciono usar responsiveSize, lo mismo deberías hacer con la fuente y con todo tamaño o dimensionamiento que dependa del tamaño de la pantalla (que usualmente son la mayoría de objetos)

**Comment by Liichi** [comment]
Arreglado
