### ISSUE TITLE
2do parametro de fetch vacio

### ISSUE THREAD

**Issue by Pablo14697** [Liichi/CocktailFinder#21]
https://github.com/Liichi/CocktailFinder/blob/ed1265b1f8bd3f288fa37cc5e4e96b9db16cf097/src/actions/search.ts#L84

{} vacio => borrarlo

**Comment by Liichi** [comment]
Arreglado

**Comment by Pablo14697** [comment]
Otro comment: nosotros acostumbrados a usar estos operadores `` para trabajar con string.
De forma que ya no se use ese signo "+" y pueda ser reemplazado por `${Config.API_URL}${searchText}`. Esto viene de ES6
