### ISSUE TITLE
Props destructuring 

### ISSUE THREAD

**Issue by IanCiarulli** [Liichi/CocktailFinder#5]
https://github.com/Liichi/CocktailFinder/blob/c68fe20764f880d2de5694162be56d30b6c6af5c/src/screens/search.tsx#L47

Destructurar las props

**Comment by Liichi** [comment]
trendria que hacer un array para cada variable de la estructura?

**Comment by IanCiarulli** [comment]
No,lo que vos le pasas a la flatlist es un objeto, tenes que destructurar ese objeto, 
`const { data } = this.props` , entonces le pasas `data={data}`

**Comment by Liichi** [comment]
Ahh ya entendi, gracias!

**Comment by Liichi** [comment]
Arreglado
