### ISSUE TITLE
Styles en otro archivo

### ISSUE THREAD

**Issue by Pablo14697** [Liichi/CocktailFinder#6]
https://github.com/Liichi/CocktailFinder/blob/c68fe20764f880d2de5694162be56d30b6c6af5c/src/screens/index.tsx#L43

Quedaría mejor si creas una carpeta por cada screen como WelcomeScreen en el que va a estar la principal pantalla que va a llevar al buscador.
En dicha carpeta creas styles.ts y un index.ts. Cuestion de que quede todo ordenadito.

Lo mismo para el buscador

**Comment by Liichi** [comment]
Arreglado
