### ISSUE TITLE
Empty state

### ISSUE THREAD

**Issue by IanCiarulli** [Liichi/CocktailFinder#9]
https://github.com/Liichi/CocktailFinder/blob/c68fe20764f880d2de5694162be56d30b6c6af5c/src/screens/search.tsx#L19-L21
Si no se usa el State para nada,podes borrar la interface, y quitarla del extends https://github.com/Liichi/CocktailFinder/blob/c68fe20764f880d2de5694162be56d30b6c6af5c/src/screens/search.tsx#L23

**Comment by Liichi** [comment]
Arreglado
